# frozen_string_literal: true

tap 'buo/cask-upgrade' # auto-upgrade casks

brew 'bat' # `cat` replacement
brew 'btop' # `htop` replacement
brew 'curl' # CLI for transferring data
brew 'dockutil' # CLI for MacOS Dock management
brew 'eza' # `ls` replacement
brew 'fd' # `find` replacement
brew 'fzf' # Fuzzy finder
brew 'gh' # GitHub CLI
brew 'git' # Version control
brew 'gum' # Go based interactive shell script generator
brew 'gs' # Postscript and PDF interpreter
brew 'htop' # `top` replacement
brew 'imagemagick' # Image processing
brew 'jq' # JSON processor
brew 'just' # Command runner
brew 'lazygit' # Git Terminal UI
brew 'libyaml' # dependency for ruby
brew 'lima' # Linux virtual machine manager
brew 'luarocks' # dependency for nvim
brew 'mas' # Mac App Store
brew 'mise' # version, environment manager
brew 'neovim' # Preferred text editor
brew 'podman' # Container management CLI
brew 'podman-compose' # Compose for Podman
brew 'ripgrep' # `grep` replacement
brew 'stow' # Symlink manager
brew 'tectonic' # LaTeX engine
brew 'uutils-coreutils' # GNU core utilities Rust replacement
brew 'vivid' # `LS_COLORS` generator
brew 'wallpaper' # macOS wallpaper manager
brew 'wget' # GNU Wget
brew 'yazi' # File manager in terminal
brew 'yq' # YAML processor
brew 'zoxide' # `cd` replacement
brew 'zsh' # Shell

cask '1password' # Password manager
cask '1password-cli' # 1Password CLI
cask 'betterdisplay' # Display configuration manager
cask 'docker-desktop' # Containerization
cask 'google-chrome' # Browser
cask 'ghostty' # Terminal emulator
cask 'gpg-suite' # GPG keychain
cask 'hammerspoon' # macOS automation
cask 'imageoptim' # Image optimizer
cask 'insomnium' # HTTP Client
cask 'obsidian' # Note-taking
cask 'podman-desktop' # Container management GUI
cask 'wezterm@nightly', args: { no_quarantine: true, greedy_latest: true } # Terminal emulator

mas '1Password for Safari', id: 1_569_813_296

# Personal profile
if ENV['HOMEBREW_PROFILE'] == 'personal'
  cask 'discord' # Chat
  cask 'whatsapp' # Messenger
end
