[settings]
lockfile = true

[env]
HK_MISE = 1
HK_STAGE = 0

[tools]
pkl = "latest"
hk = "latest"
shellcheck = "latest"
stylua = "latest"
yamllint = "latest"

[hooks]
enter = { script = 'set_terminal_title "󰒓  {{ config_root | basename }}"', shell = "zsh" }
leave = { script = "reset_terminal_title", shell = "zsh" }

[tasks.check]
description = "Run all checks"
run = "hk run check"

[tasks.fix]
description = "Fix all (fixable) issues"
run = "hk run fix"

[tasks.pre-commit]
description = "Run pre-commit hooks"
run = "hk run pre-commit"

[tasks.setup]
description = "Set up the development environment"
run = ["bun install", "hk install"]

[tasks.vectorize]
description = "Vectorise codebase"
run = "vectorcode vectorise"
