[settings]
lockfile = true

[env]
HK_MISE = 1
HK_STAGE = 1

[task_config]
includes = ["scripts/tasks"]

[tools]
bun = "latest"
betterleaks = "latest"
markdownlint-cli2 = "latest"
pkl = "latest"
hk = "latest"
shellcheck = "latest"
stylua = "latest"
yamllint = "latest"
