# frozen_string_literal: true

# TODO: lima

tap 'buo/cask-upgrade' # auto-upgrade casks

brew 'bat' # `cat` replacement
brew 'coreutils' # GNU core utilities
brew 'curl' # CLI for transferring data
brew 'eza' # `ls` replacement
brew 'fd' # `find` replacement
brew 'fzf' # Fuzzy finder
brew 'gh' # GitHub CLI
brew 'git' # Version control
brew 'gum' # Go based interactive shell script generator
brew 'htop' # `top` replacement
brew 'jq' # JSON processor
brew 'just' # Command runner
brew 'lazygit' # Git Terminal UI
brew 'libyaml' # dependency for ruby
brew 'luarocks' # dependency for nvim
brew 'mas' # Mac App Store
brew 'mise' # version, environment manager
brew 'neovim' # Preferred text editor
brew 'ripgrep' # `grep` replacement
brew 'stow' # Symlink manager
brew 'vivid' # `LS_COLORS` generator
brew 'wget' # GNU Wget
brew 'yazi' # File manager in terminal
brew 'zoxide' # `cd` replacement
brew 'zsh' # Shell

cask '1password' # Password manager
cask '1password-cli' # 1Password CLI
cask 'betterdisplay' # Display configuration manager
cask 'discord' # Chat app
cask 'docker' # Containerization
cask 'google-chrome' # Browser
cask 'gpg-suite' # GPG keychain
cask 'hammerspoon' # macOS automation
cask 'imageoptim' # Image optimizer
cask 'insomnium' # HTTP Client
cask 'obsidian' # Note-taking
cask 'wezterm@nightly', args: { no_quarantine: true, greedy_latest: true } # Terminal emulator

mas '1Password for Safari', id: 1_569_813_296

# Personal profile
mas 'WhatsApp Messenger', id: 310_633_997 if ENV['HOMEBREW_PROFILE'] == 'personal'
